# 使用官方 Python 运行时作为父镜像
FROM python:3.11-slim AS python-app

# 将当前目录内容复制到工作目录
COPY ./lynsie-langchain /app/lynsie-langchain

# 切换到应用目录
WORKDIR /app/lynsie-langchain

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 暴露端口
EXPOSE 8000

# 运行应用
CMD ["python", "main.py"]
