services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile.langchain
      target: python-app
    ports:
      - "8000:8000"
    container_name: python-app-container
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
      target: node-app
    ports:
      - "3000:3000"
    container_name: node-app-container

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - python-app
      - node-app

