services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile.langchain
      target: python-app
    ports:
      - "8000:8000"
    container_name: python-app-container

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
      target: node-app
    ports:
      - "3000:3000"
    container_name: node-app-container

